### ISSUE TITLE
Add some responsiveness to the index page 

### ISSUE THREAD

**Issue by AnshumanDhiman** [AnshumanDhiman/Valorant#1]

**Comment by PranavTrip** [comment]
Hey Anshuman please assign this to me

**Comment by AmanRana10** [comment]
hey @AnshumanDhiman can i work on it?

**Comment by AnshumanDhiman** [comment]
go ahead @PranavTrip

**Comment by AnshumanDhiman** [comment]
also mention the screenshot after the work is done

**Comment by AmanRana10** [comment]
can i also contribute? @AnshumanDhiman

**Comment by AnshumanDhiman** [comment]
I am sorry 1 person per issue. Find and open an issue or wait for an issue to open to work on it, I'll assign it.

**Comment by PranavTrip** [comment]
> also mention the screenshot after the work is done

Yeah sure I am working on it. Thanks

**Comment by AmanRana10** [comment]
Is the issue resolved ??
